apiVersion: v1
kind: Service
metadata:
  name: hello
  namespace: hello-app
  labels:
    name: hello-app
spec:
  ports:
  - port: 80
    name: plaintext
    targetPort: 8080
  selector:
    app: hello
  type: LoadBalancer